# This is a basic workflow to help you get started with Actions

name: Deploy to Firebase (hosting/storage)

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - main
      - release/*
      - firebase-deploy
  pull_request:
    branches:
      - main
      - firebase-deploy

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy_to_firebase:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Set up js package
      - name: checkout repo
        uses: actions/checkout@v2

      - name: use node.js
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      # install, test, build package
      - name: npm install
        run: npm install
      - name: npm build
        run: npm run build
      - name: npm test
        run: npm test
        env:
          CI: true

      # deploy
      - name: deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
