name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        eeg: [true, false]
        os: [ubuntu-latest, macOS-latest, windows-2019]
        exclude: 
          # exclude eeg builds for mac and linux
          - os: ubuntu-latest
            eeg: true
          - os: macOS-latest
            eeg: true
            
    steps:
      # Rewrite "git:" repo urls to use "https:" instead, since GitHub Actions blocks port 9418 (as of Jan 2022).
      - name: Rewrite "git:" repo urls to use "https:" instead.
        run: git config --global url."https://github.com/".insteadOf "git://github.com/"

      # Set up js package
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      # install, test, build package
      - name: npm install
        run: npm install
      - name: npm build
        run: npm run build
        env:
          REACT_APP_AT_HOME: ${{ matrix.eeg }}
      - name: npm test
        run: npm test
        env:
          CI: true
          REACT_APP_AT_HOME: ${{ matrix.eeg }}
