name: firebase-deploy-merge-demand
'on':
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      firebase-env:
        description: Sufix of firebase environment file - 'firebase-lncc', 'firebase-tricamlab'
        required: false
        default: 'firebase-apach'
      firebase-channel:
        description: Which firebase-channel to deploy to - 'live', 'qa',
        required: false
        default: 'qa'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Python 2.7 Setup mit Docker
      - name: Setup Python 2.7
        run: |
          docker pull python:2.7-slim
          docker run -d --name py27 python:2.7-slim tail -f /dev/null
          docker exec py27 python --version
          docker exec py27 pip install setuptools wheel
          echo "PYTHON_PATH=$(docker exec py27 which python)" >> $GITHUB_ENV
      
      # Build Dependencies
      - name: Install build essentials
        run: sudo apt-get install -y build-essential
      
      # Node.js Setup
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      
      # node-gyp Konfiguration
      - name: Configure node-gyp
        run: |
          npm config set python ${{ env.PYTHON_PATH }}
          npm install -g node-gyp@6.1.0
      
      # Rewrite "git:" repo urls to use "https:" instead
      - name: Rewrite "git:" repo urls to use "https:" instead.
        run: git config --global url."https://github.com/".insteadOf "git://github.com/"
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: 'npm install' 

      - name: Load .env file for build settings
        uses: xom9ikk/dotenv@v1.0.2
        with:
          path: ./env
          mode: ${{ github.event.inputs.firebase-env || 'firebase-apach' }}

      - run: 'npm run build'
      # Deployment starting failing for node 14 - see https://github.com/firebase/firebase-tools/issues/5010
      - name: Setup node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TASK_EFFORT_APACH }}'
          channelId: ${{ github.event.inputs.firebase-channel || 'live' }}
          projectId: task-effort-apach

          firebaseToolsVersion: '12.9.1'  # Added this line

