name: firebase-deploy-merge-demand
'on':
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      firebase-env:
        description: Sufix of firebase environment file
        required: false
        default: 'firebase-apach'
      firebase-channel:
        description: Which firebase-channel to deploy to
        required: false
        default: 'qa'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          
      - name: Clean Install
        run: |
          rm -rf node_modules
          npm config set legacy-peer-deps true
          npm config set package-lock false
          npm install
          
      - name: Build
        run: npm run build
        env:
          CI: false
        
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TASK_EFFORT_APACH }}'
          channelId: ${{ github.event.inputs.firebase-channel || 'live' }}
          projectId: task-effort-apach
          firebaseToolsVersion: '12.9.1'

